const REQUEST = 'REQUEST'
const SUCCESS = 'SUCCESS'
const FAILURE = 'FAILURE'
const CLEAR_ERROR = 'CLEAR_ERROR'
const PROGRESS = 'PROGRESS'
const INITIALISE = 'INITIALISE'
const INITIALISED = 'INITIALISED'
const RESET = 'RESET'
const PUBLISH = 'PUBLISH'
const RETRACTED = 'RETRACTED'

export { REQUEST, SUCCESS, FAILURE, CLEAR_ERROR, PROGRESS, INITIALISE, INITIALISED, RESET, PUBLISH, RETRACTED }
