version: '3.3'

services:

  legion-mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ../.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=LegionRoot
      - MONGO_INITDB_ROOT_PASSWORD=${LEGION_ROOT_DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=Legion
    volumes:
      - type: bind
        source: ./Home/
        target: /home/mongodb/
      - type: bind
        source: ./Init/
        target: /docker-entrypoint-initdb.d/

  legion-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - ../.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=LegionRoot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${LEGION_ROOT_DATABASE_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=legion-mongo

